#!/usr/bin/env python3
"""Generated by Siphon — Automatic API flow replay script"""

import requests

session = requests.Session()

# ── Step 1: GET https://httpbin.org/get ──

response_0 = session.get(
    "https://httpbin.org/get")

print(f"Step 1: {response_0.status_code} GET https://httpbin.org/get")

print("\nFlow complete!")
