#!/usr/bin/env bash
# Generated by Siphon — Automatic API flow replay script
set -euo pipefail

# ── Configurable Parameters ──
USERNAME="${USERNAME:-testuser}"

COOKIE_JAR=$(mktemp)
trap 'rm -f "$COOKIE_JAR"' EXIT

# ── Step 1: GET https://httpbin.org/forms/post ──
STATUS_0=$(curl -s -o /dev/null -w "%{http_code}" \
  -X GET \
  -b "$COOKIE_JAR" -c "$COOKIE_JAR" \
  "https://httpbin.org/forms/post")

echo "Step 1: $STATUS_0 GET https://httpbin.org/forms/post"
[[ "$STATUS_0" != "200" ]] && echo "Expected 200, got $STATUS_0" && exit 1

# ── Step 2: POST https://httpbin.org/post ──
STATUS_1=$(curl -s -o /dev/null -w "%{http_code}" \
  -X POST \
  -b "$COOKIE_JAR" -c "$COOKIE_JAR" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "custname=$USERNAME&custtel=&custemail=&delivery=&comments=" \
  "https://httpbin.org/post")

echo "Step 2: $STATUS_1 POST https://httpbin.org/post"
[[ "$STATUS_1" != "200" ]] && echo "Expected 200, got $STATUS_1" && exit 1

echo ""
echo "Flow complete!"
