#!/usr/bin/env python3
"""Generated by Siphon — Automatic API flow replay script"""

import requests

# ── Configurable Parameters ──
USERNAME = "testuser"

session = requests.Session()

# ── Step 1: GET https://httpbin.org/forms/post ──

response_0 = session.get(
    "https://httpbin.org/forms/post")

print(f"Step 1: {response_0.status_code} GET https://httpbin.org/forms/post")
assert response_0.status_code == 200, f"Expected 200, got {response_0.status_code}"

# ── Step 2: POST https://httpbin.org/post ──

headers_1 = {
    "Content-Type": "application/x-www-form-urlencoded",
}

body_1 = f"""custname={USERNAME}&custtel=&custemail=&delivery=&comments="""

response_1 = session.post(
    f"https://httpbin.org/post",
    headers=headers_1,
    data=body_1)

print(f"Step 2: {response_1.status_code} POST https://httpbin.org/post")
assert response_1.status_code == 200, f"Expected 200, got {response_1.status_code}"

print("\nFlow complete!")
